### ISSUE TITLE
Deathly Sleep Should Not Automatically Recast

### ISSUE THREAD

**Issue by hjozwiak** [stormdragon2976/tintin-alteraeon#5]
When deathly sleeping, the client currently recasts it once it falls; this is by no means logical, and it is liable to be extremely dangerous.

**Comment by stormdragon2976** [comment]
This should be fixed on the 2017 branch. This will become the stable release on the 20 of this month.

**Comment by hjozwiak** [comment]
Ah, gotcha. Thanks.
